### ISSUE TITLE
module not working with titanium sdk 6.0 GA or above

### ISSUE THREAD

**Issue by aakashsharmaindore** [applification/TiStarter#1]
Hello,
I have been trying to implement the pull to functionality in one of my app, but the module is not compiled for Titanium SDK 6.0.0 and above. I cannot change my SDK for now so can you compile the module with the latest version and push it live.

Thanks,
Aakash Sharma

**Comment by DaveHudson** [comment]
Hi Aakash, 

The pull module is not mine. This sample project uses https://github.com/FokkeZB/nl.fokkezb.pullToRefresh widget which had a dependency on the module https://github.com/raymondkam/Ti.SwipeRefreshLayout

I see a PR for the issue you mention has been outstanding for 6 months on that repo https://github.com/raymondkam/Ti.SwipeRefreshLayout/pull/16 so seems unsupported.

The nl.fokkezb.pullToRefresh widget now appears to use a fork of that module which is at
https://github.com/iskugor/Ti.SwipeRefreshLayout so you might find what you need there...
